### ISSUE TITLE
Compass translation 

### ISSUE THREAD

**Issue by Geonauta** [KcNirvana/MIUI-XML-13-PORTUGUESE#1]
Hi. 
Compass application does not display the correct letters for East indications. When pointing to the West it shows the correct letters 'O' 'NO' 'SO' ('W' 'NW' 'SW'), but when the compass is pointing to the East show the same letters 'O' 'NO' ''SO' this is wrong. It's a bug that needs to be fixed.

This is in a Redmi Note 8, with xiaomi.eu stable rom, Miui 12.5.

I was hoping that the last update would fix it, but it's already updated and the problem remains.

In English it's all fine. 

https://xiaomi.eu/community/threads/compass-bug.62843/

Many thanks.

**Comment by KcNirvana** [comment]
Boas,
Eu não consigo reproduzir na Miui13.
Mas podes validar se com o idioma PT-BR se acontece exatamente a mesma coisa?
Obrigado.

Abraço

**Comment by Geonauta** [comment]
É mesmo na MIUI 12.5
Fui experimentar em PT-BR e também está a acontecer (fotos). 

![Screenshot_2022-03-03-14-18-51-902_com miui compass](https://user-images.githubusercontent.com/100621922/156584214-33bc90b7-ec7e-424f-b3bd-391cb5f3c28a.jpg)
![Screenshot_2022-03-03-14-18-43-243_com miui compass](https://user-images.githubusercontent.com/100621922/156584222-d6f53657-9319-4978-82d3-2e3ca2b2ab46.jpg)
![Screenshot_2022-03-03-14-18-37-950_com miui compass](https://user-images.githubusercontent.com/100621922/156584228-1f7c4cf8-1601-4177-8754-6c7ec2530034.jpg)
![Screenshot_2022-03-03-14-18-26-506_com miui compass](https://user-images.githubusercontent.com/100621922/156584232-895b04a0-704c-466e-8c20-c281aff1ca87.jpg)
![Screenshot_2022-03-03-14-18-20-147_com miui compass](https://user-images.githubusercontent.com/100621922/156584242-ebf8a2d4-8b03-41c5-ac8e-88c7011d5e24.jpg)
![Screenshot_2022-03-03-14-18-10-837_com miui compass](https://user-images.githubusercontent.com/100621922/156584246-31ded897-883f-4f99-a2bc-ed8ec666f538.jpg)
![Screenshot_2022-03-03-14-17-56-872_com miui compass](https://user-images.githubusercontent.com/100621922/156584249-64c95103-4cc2-4ef4-b1c5-1ba6f1e865af.jpg)

**Comment by KcNirvana** [comment]
Boas,
O problema estava na tradução brasileira.
Se houver mais alguma release da Miui 12/13 fica resolvido.
Obrigado pela indicação e vai reportando mais problemas de tradução que encontres.
Obrigado.

Abraço

**Comment by Geonauta** [comment]
Obrigado eu.

Abraço.
